@url_dev=http://localhost:3000/api/v1/products

### Tạo mới sản phẩm
POST {{url_dev}}/create
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTEwMjM5NywiZXhwIjoxNzM1Mjc1MTk3fQ.KqZoKW1AKF8ZAOye1oeFg1RXcli1YBFee5v0woF2I6EdrkXcYVxC2iDtkA43E0NKaO2dym8LEXAvYiRCjW6VFRh2cf5Bh2L1luI1FzuYrt3zqI6LgMMht2cJNfv0K1D40GMu_mkw4JregNT0eL5TDJD9_9Acouz4mc1GhNKyAFdusZWBSR9-3_6BuC1Yfs-4zgBiu71y9m0uwcZgh4UnSbpgHr-Y-nh5cnS14zccfsJpt4rYlamFo-468dczrXxki1r38IGz76XAJ8_BWFBBRqjnlkoxhHywKjfRJSUbn8Dxo5Z1h-JBUQTGjlLIRsdO5uckHDpDz6swAxMlqqBToyenDqBKjDkneHk8-rI0bv8t5ZzpKd9chSIpNvpk7hMEcm1ojxOlWMKmnImyCivHJT5VFriQWGMwR17WjkRC_X1y0nts2t6fAlX03xMbvsF_xO6uolCQjfjl16cfdvev1t1STVZD9zNvs0N2ujxjj7y5dpqPrxIAffqFZCWDXx7qjAUMX2L3QUFYNo7OD2B0Tr7b-o3V886VsNMUEhX90w7aGeMAfosnuTb86RUsp4Fnnl-mu20P7iwB5HXHP5UqikRDvNgwZsASrh8wkpQWL-w-vuqEz1IFwCgu7Les2HmvX3Zn2uUYsCfmeyZEkDpUOcj-NYBI69-NXShKQSosC4Y

{
    "product_name": "Áo Polo",
    "product_description": "High-quality denim jeans",
    "product_price": 50,
    "product_shop": "676ab54ce8d726e64be6d910",
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attributes" : {
        "brand": "Levil",
        "size": "L",
        "material": "Denim"
    }
}

### Publish một sản phẩm
POST {{url_dev}}/isPublish/676d3d1768df1a766298631c
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTEwMjM5NywiZXhwIjoxNzM1Mjc1MTk3fQ.KqZoKW1AKF8ZAOye1oeFg1RXcli1YBFee5v0woF2I6EdrkXcYVxC2iDtkA43E0NKaO2dym8LEXAvYiRCjW6VFRh2cf5Bh2L1luI1FzuYrt3zqI6LgMMht2cJNfv0K1D40GMu_mkw4JregNT0eL5TDJD9_9Acouz4mc1GhNKyAFdusZWBSR9-3_6BuC1Yfs-4zgBiu71y9m0uwcZgh4UnSbpgHr-Y-nh5cnS14zccfsJpt4rYlamFo-468dczrXxki1r38IGz76XAJ8_BWFBBRqjnlkoxhHywKjfRJSUbn8Dxo5Z1h-JBUQTGjlLIRsdO5uckHDpDz6swAxMlqqBToyenDqBKjDkneHk8-rI0bv8t5ZzpKd9chSIpNvpk7hMEcm1ojxOlWMKmnImyCivHJT5VFriQWGMwR17WjkRC_X1y0nts2t6fAlX03xMbvsF_xO6uolCQjfjl16cfdvev1t1STVZD9zNvs0N2ujxjj7y5dpqPrxIAffqFZCWDXx7qjAUMX2L3QUFYNo7OD2B0Tr7b-o3V886VsNMUEhX90w7aGeMAfosnuTb86RUsp4Fnnl-mu20P7iwB5HXHP5UqikRDvNgwZsASrh8wkpQWL-w-vuqEz1IFwCgu7Les2HmvX3Zn2uUYsCfmeyZEkDpUOcj-NYBI69-NXShKQSosC4Y


### UnPublish một sản phẩm
POST {{url_dev}}/isUnPublish/676d3d1768df1a766298631c
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTEwMjM5NywiZXhwIjoxNzM1Mjc1MTk3fQ.KqZoKW1AKF8ZAOye1oeFg1RXcli1YBFee5v0woF2I6EdrkXcYVxC2iDtkA43E0NKaO2dym8LEXAvYiRCjW6VFRh2cf5Bh2L1luI1FzuYrt3zqI6LgMMht2cJNfv0K1D40GMu_mkw4JregNT0eL5TDJD9_9Acouz4mc1GhNKyAFdusZWBSR9-3_6BuC1Yfs-4zgBiu71y9m0uwcZgh4UnSbpgHr-Y-nh5cnS14zccfsJpt4rYlamFo-468dczrXxki1r38IGz76XAJ8_BWFBBRqjnlkoxhHywKjfRJSUbn8Dxo5Z1h-JBUQTGjlLIRsdO5uckHDpDz6swAxMlqqBToyenDqBKjDkneHk8-rI0bv8t5ZzpKd9chSIpNvpk7hMEcm1ojxOlWMKmnImyCivHJT5VFriQWGMwR17WjkRC_X1y0nts2t6fAlX03xMbvsF_xO6uolCQjfjl16cfdvev1t1STVZD9zNvs0N2ujxjj7y5dpqPrxIAffqFZCWDXx7qjAUMX2L3QUFYNo7OD2B0Tr7b-o3V886VsNMUEhX90w7aGeMAfosnuTb86RUsp4Fnnl-mu20P7iwB5HXHP5UqikRDvNgwZsASrh8wkpQWL-w-vuqEz1IFwCgu7Les2HmvX3Zn2uUYsCfmeyZEkDpUOcj-NYBI69-NXShKQSosC4Y