@url_dev=http://localhost:3000/api/v1/shop

### đăng ký
POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f

{
    "name": "Giang Trường Shop",
    "email": "giangtruong100702@gmail.com",
    "password": "matkhauSieuManh"
}

### đăng nhập
POST {{url_dev}}/login
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f

{
    "email": "giangtruong100702@gmail.com",
    "password": "matkhauSieuManh"
}

### đăng xuất
POST {{url_dev}}/logout
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTA0NzQyMCwiZXhwIjoxNzM1MjIwMjIwfQ.CaMC9N0TX8qeJ1TY_bSFJLqtPOw6dETYqhjAU2gvgVCsnd0NPkN4tg2V48aCt3NHbcCO7_UTb1KHNsEVTpLJNm_zqGevgXe1R7Zdy4dbrm9qEiw7VuPZZee5RLDDfXJ7oAWcVqNngDJ464R99GF7ViLa4rsJ-G_UPAcn0do-88-GT0fi4ciQ1mkNbNHxBCQNOCPGea6dfyM4IJSMxU2UqUByZojuVZxNbLDS6tztTLw0d3xpb0lMsgUHI-3Esp8Suroe3cYxPorjrFFwNXBV2NBscTQL_e4EIAOlZzk3dxDpwDCoOLN2NjxGFVLa0aN5Rm8jExSRblblcSbyejbZIpxvOi2h1iZd3vr7D1U-C-dPeqn91qbmFitXsMDMkZVXL4xhi8T4398WlRGO2ENTfU-CfDfvYr5L67VFvWLFJIVh1FVm9Za2cEAQ-0NWVi27pEqGlJS_EZ6TfRhWJWZS1p6v0t9PLeBsR9NM_4gkGUpHxSMIsl7NwtSOPqvjfoH0xu-tMVV0GBhr2tpZC-C-Axjp0piuX1He6DE8UpSBkX2rQpoMJMtSs56iYigvVC4sqkJDUvQ4i58YlyoWA72yFPxlIAOOjHzU3RR0txOe3iH1RaQ8yh9pkxPqV3-K6dKxQ_xTBEwHYkIFNOoCMuVvlKVOQjVwBeTDzpUcTLc0LQs

### refresh token
POST {{url_dev}}/refreshToken
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTA2MDIwMywiZXhwIjoxNzM1MjMzMDAzfQ.QiCOWtdqaJ_WgDbNxVF8MCYkig5csC1xBkdHWgawAZdGW-tQFuz7Sq9epS0G4vL6v0pyPtl7UBXicRWz9Yrx-v5zX0sdd6c2k-1TBt1v4ApBpy8MwP4h3jzpuxsAprttddwrLoke_zHkfGJQKRhKapHCwKB4yRssCizEawcWmlWU4iN6rQGX0ZnJoYTNGGEitEO7YT4kXYJAnV3xVpDZjIaPGrvo8UN0C7PnRjQ7t1S__CvC--PU-62nsneA-mjkevDQo-afESkF17IL9SmyoZHgdIpRdw1GoVo5-Ltyp93X0o6Z90NpOkqO400sgnjSO8OYp_uVgZ78oKlmcO9EKCtknpPFNJPc3ejdy8xaTlrSOejYQ-0SXkry82EDiVtDllY6hXy_d6ayQsq8--0OtZIq55ds5w75WdJDkb3h-NPbueXjKfC7DVp1TuT6eYaTDTcACiTQjVwnMFyHH9FOHbpe78LM6P2uGEWVzIe1Aayt2Oeh2iFb8-udMtsCIL6OF05MD0PKPlmKPZH01JVkUMDMtoZfOm5AiGKpJVfMmgOXlwJ3ITChdAvykyo_I1q8Kto-Msd999lZ7Z2n33FI83d_nS2Qh-S7Gtj8LopUZzSFwLO0jx9RAK04197oaevYaJfhDw-8qUmxggd6ZO3j_jrDIPGT3YYIISHkM-XyoyQ
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTA2MDIwMywiZXhwIjoxNzM1NjY1MDAzfQ.KVU_c9-rmI1xoh_Mr88rbqqSIO3qTxeGal0d4L7wzMIJPqT37P981MO_VX0nC2RFlmfcQL-PAzjdjGogg75SU3v8Sa22trI356p2flji2JcoadT5zbEOJ-DSnWvplOLABkChcWJF44FfPGJsAHxUI0GToV5f6KqFLoynruv8sFO83ypnAwyX_VfCirthgBKcn3xrbGbfNI8tBpQ5anbsVA9IQSnNnQbZVsdcbDIALgZAZUsg_nC6FCeVJlnyuQXbrmGv_w-TeoUJQ6rz2Awx_36GKjIEMvefih9Ud9E113jYT7mI8M8LWoqGB9-JDbBtrodHXNNxw3oYErU_2m1EvrGxf1dA3Z15cUJdgXanvF5m-AV6Yz0XN4Tr8lRMg2JM54dcoxGil4hwR78SCYyW_UJfMGUQZ-f2qf_a7OIzlD0eSMuha9JrHrZpvR3CcwCilrlsg7_ki3b3W_RmlFyipvBpiMTVTYwPvzh192RlLp1nth1of3oNRgI7BZIWxvdAfQaQdDKfG3HtOipplwEQE-YDakFIwmm5N_3DL_UWa9CMlbh7ypiX__Wi00ySwrx1GUDlQcEhKM8A7CQ2Ew-eEnPLcyHpOC_W2Jifqj2n3wYdgM-o8m6HLK11IZudOYAcgdNtKfFe4gryYAOFmJp82cy6fx_MGdjGBlWQ2QJNyaQ