@url_dev=http://localhost:3000/api/v1/shop

### đăng ký
POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f

{
    "name": "Giang Trường Shop",
    "email": "giangtruong100702@gmail.com",
    "password": "matkhauSieuManh"
}

### đăng nhập
POST {{url_dev}}/login
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f

{
    "email": "giangtruong100702@gmail.com",
    "password": "matkhauSieuManh"
}

### đăng xuất
POST {{url_dev}}/logout
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 675edb05c68c6a9bb9f47aa5
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzVlZGIwNWM2OGM2YTliYjlmNDdhYTUiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNDI2OTcwMiwiZXhwIjoxNzM0NDQyNTAyfQ.j4BCso7ohuZqWhKOg9h4VR_Y43TqG06v-q6qnm6lbqPOOHYVnNVaHnbbLcR7lDA4ZEmCwKoMO5q1d-0jUrQ4hGbXgw9mx1QodatlXRMvJOCH9StX-aMmWRs9MYHecuoXU5pAE0vM3XT9f-HC0TCEuPp-8o_6_nJ1U6kDFudJZg1hz8otWlDoeyP-7gYTsw72lDDurrUvNbEHidBZZD3hIZQQJgNCZQNuC1zW0BLPQMaqtBSv_kyxiFFs33LBzu30qqyIJlbXmvYx7kBEik5kl08xdqjjDmU3lJtON9TACpbUtSFFXfVikKFA6QF8AyBoTEVrLUTwCynkdpdGpG0fCI613rZOezO9gK2XEbdnE_EpjIXvqDIEZeRviEaGn-vlmEzevj-S2WFq-W1TyoI8b9GNDbDYCOMbYayzA61fyXxufNSh8AwaEuCnogFEOr4Fv1-mK8u8yusRbFNldKJW_cWln455O8p-dl-8gw_-35_g4GDMjr4HaGIrZVNuTwu-hohMeCDwS2IdQ9cXtsz9z0pfZEMhEepbSFRGnWLuI2365UghC9FtOxYLt9z3NEWe400iBHhA-m1BAM4UleuJFbZ_bNPSIA-KWUc4Ff7EVLBv5KxQ2qDQt0aBHP2yP0xNw8kb2u_0fs0-gssY6W0BfhSMVtbSvwzDVZfBNYgi4b8