@url_dev=http://localhost:3000/api/v1/cart

### XÓa item khỏi giỏ hàng 
DELETE {{url_dev}}/delete
Content-Type: application/json
x-api-key: 106b78f9ffe2a70ea6c39072b14af60a16742ebf5dd426a9b03ab8d90775748220e15a7e0c33498ced67cbf1f10e552c16e22c70a2d08e431a8b55e68ed8a75f
x-client-id: 676ab54ce8d726e64be6d910
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhYjU0Y2U4ZDcyNmU2NGJlNmQ5MTAiLCJlbWFpbCI6ImdpYW5ndHJ1b25nMTAwNzAyQGdtYWlsLmNvbSIsImlhdCI6MTczNTYyODIxMywiZXhwIjoxNzM1ODAxMDEzfQ.OCI03fUa8LtEhCKfAT1KlzuHXu5kPUDu95egY6e-ogUof5cEEMGeqi8YbjdSlyIlxHaXHJdPQQlICQIcejTkOkIXeKq1ilW8n-inM35u6YkOWWbbU7OOmwIql36BrOnaHN-cjZe3mbmcxnlHAU-CfwbH5DDMhZi7-Kn9-u0p-k9bmAxuvkFLQ3OwWUqzKizXbVr-az4or3f7wLdQOVI-t8hlZ-OPgy0EVz5vTisF5aV0c7ZxqnjQvfzrDZQ9gHi8PRIN-9H9S_4N5puO7Z2S_qLMBh8niKnhAmZdzxIdkRrf1YFn0U9K9gZzIDtiqB9orN8k0YTF1Ks6p-d2Cup_3Uy6hvOfQAlcstqkNFPwF5kq36ks1feHbYlIAX0-mJrF7gSaawfyRaU5Zrr4fCpUFi4IjcI6XtNdvFgnxVV054MkMmR8RQWCm7meRDF869IaRNArvS2lXETcg81WBplGmISEwO0ZR_eHLAofVdrdpCo1cmMaPvXTFX7kEKFNhPH7JoOrQ3-J9Qcz-wsf4ti2qtwe6RnXwbPYuEpzLw6gtFJ46fAqeZVc9Mtxb67RhnX6YggIFTA3E7gcgaawmyfI6bi5FQPioGBWxAuXP1YyE3lks1iBEfZMQpQFPCRyrVH8ZVuM3GlPTb7sTx4pobx76_uvpzX5KBm4QJFTMnbLSfc

{
    "userId": 1001,
    "productId": "676ed07851396cc33e0d5232"
}